platform :ios, '8.0'
use_frameworks!

target 'AppUtils' do
	pod 'Alamofire'    
  

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
  end
end


